In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB, GaussianNB
!pip install streamlit
import streamlit as st

In [2]:
df = pd.read_csv("spam.csv")
df.head()

,Category,Message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [3]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [4]:
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [5]:
df['spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df.head()

,Category,Message,spam
0,ham,"Go until jurong point, crazy.. Available only ...",0
1,ham,Ok lar... Joking wif u oni...,0
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,1
3,ham,U dun say so early hor... U c already then say...,0
4,ham,"Nah I don't think he goes to usf, he lives aro...",0


In [6]:
df.drop(columns=['Category'],inplace=True)
df.head()

,Message,spam
0,"Go until jurong point, crazy.. Available only ...",0
1,Ok lar... Joking wif u oni...,0
2,Free entry in 2 a wkly comp to win FA Cup fina...,1
3,U dun say so early hor... U c already then say...,0
4,"Nah I don't think he goes to usf, he lives aro...",0


In [7]:
x_train,x_test,y_train,y_test = train_test_split(df.Message,df.spam,test_size=.3,random_state=34)

v = CountVectorizer()
X_train_count = v.fit_transform(x_train)
X_train_count.toarray()


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(3900, 7184))

In [8]:
model=MultinomialNB()
model.fit(X_train_count,y_train)

,"alpha alpha: float or array-like of shape (n_features,), default=1.0Additive (Laplace/Lidstone) smoothing parameter(set alpha=0 and force_alpha=True, for no smoothing).",1.0
,"force_alpha force_alpha: bool, default=TrueIf False and alpha is less than 1e-10, it will set alpha to1e-10. If True, alpha will remain unchanged. This may causenumerical errors if alpha is too close to 0... versionadded:: 1.2.. versionchanged:: 1.4 The default value of `force_alpha` changed to `True`.",True
,"fit_prior fit_prior: bool, default=TrueWhether to learn class prior probabilities or not.If false, a uniform prior will be used.",True
,"class_prior class_prior: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None


In [9]:
x_test_count = v.transform(x_test)
model.score(x_test_count,y_test)

0.9892344497607656

In [10]:
from sklearn.metrics import accuracy_score, precision_score , recall_score,f1_score,confusion_matrix
y_pred=model.predict(x_test_count)
print("Accuracy : ", accuracy_score(y_test,y_pred))
print("Precision : ", precision_score(y_test,y_pred))
print("Recall : ", recall_score(y_test,y_pred))
print("F1- score : ",f1_score(y_test,y_pred))
print("\n" ,confusion_matrix(y_test,y_pred))

Accuracy :  0.9892344497607656
Precision :  0.9905660377358491
Recall :  0.9292035398230089
F1- score :  0.958904109589041

 [[1444    2]
 [  16  210]]


In [11]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!',
    'i have offer for you 1000 rupees off and free travel,hurry up!!'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1, 1])

In [12]:
import joblib

In [13]:
final='model.sav'
joblib.dump(model,open(final,'wb'))

joblib.dump(v,open('vectorizer.pkl','wb'))

